from PyQt5 import QtCore, QtGui, QtWidgets
from docx import Document
from docx.shared import Inches
from os import *
from datetime import datetime
import win32api
import win32print



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 764)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.364, y1:0.494318, x2:1, y2:0, stop:0 rgba(75, 180, 210, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 851, 761))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(99, 99, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.textEdit_resultat = QtWidgets.QTextEdit(self.Home)
        self.textEdit_resultat.setEnabled(True)
        self.textEdit_resultat.setGeometry(QtCore.QRect(90, 60, 651, 661))
        self.textEdit_resultat.setStyleSheet("font: 16pt \"MV Boli\";\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.textEdit_resultat.setObjectName("textEdit_resultat")
        self.lineEdit_res_2 = QtWidgets.QLineEdit(self.Home)
        self.lineEdit_res_2.setGeometry(QtCore.QRect(310, 10, 201, 41))
        self.lineEdit_res_2.setStyleSheet("color: rgb(255, 92, 92);\n"
"font: 28pt \"Palatino Linotype\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border-radius:5px;\n"
"border-color: rgb(255, 175, 46);\n"
"")
        self.lineEdit_res_2.setObjectName("lineEdit_res_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.Home)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 181, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(190, 255, 178);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.Home, "")
        self.USI = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.364, 0.494318, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(75, 180, 210))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(162, 255, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.USI.setPalette(palette)
        self.USI.setObjectName("USI")
        self.tabWidget_O = QtWidgets.QTabWidget(self.USI)
        self.tabWidget_O.setGeometry(QtCore.QRect(0, 50, 861, 701))
        self.tabWidget_O.setObjectName("tabWidget_O")
        self.tab_pacient = QtWidgets.QWidget()
        self.tab_pacient.setObjectName("tab_pacient")
        self.label_2 = QtWidgets.QLabel(self.tab_pacient)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 121, 51))
        self.label_2.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_pacient)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 30, 311, 31))
        self.lineEdit_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.tab_pacient)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 121, 51))
        self.label_3.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_pacient)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 110, 131, 31))
        self.lineEdit_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.tab_pacient)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 121, 51))
        self.label_4.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(self.tab_pacient)
        self.comboBox.setGeometry(QtCore.QRect(160, 180, 91, 41))
        self.comboBox.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.tab_pacient)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 121, 51))
        self.label_5.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_pacient)
        self.lineEdit_4.setGeometry(QtCore.QRect(160, 270, 131, 31))
        self.lineEdit_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_pacient)
        self.lineEdit_5.setGeometry(QtCore.QRect(160, 350, 131, 31))
        self.lineEdit_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.tab_pacient)
        self.label_6.setGeometry(QtCore.QRect(10, 340, 121, 51))
        self.label_6.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_pacient)
        self.label_7.setGeometry(QtCore.QRect(10, 410, 181, 51))
        self.label_7.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 18pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_pacient)
        self.lineEdit_6.setGeometry(QtCore.QRect(230, 420, 131, 31))
        self.lineEdit_6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_pacient)
        self.lineEdit_27.setGeometry(QtCore.QRect(510, 210, 311, 31))
        self.lineEdit_27.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_27.setText("")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_36 = QtWidgets.QLabel(self.tab_pacient)
        self.label_36.setGeometry(QtCore.QRect(630, 170, 51, 31))
        self.label_36.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab_pacient)
        self.label_37.setGeometry(QtCore.QRect(560, 260, 251, 31))
        self.label_37.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_37.setObjectName("label_37")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_pacient)
        self.lineEdit_28.setGeometry(QtCore.QRect(510, 300, 311, 31))
        self.lineEdit_28.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_28.setText("")
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_39 = QtWidgets.QLabel(self.tab_pacient)
        self.label_39.setGeometry(QtCore.QRect(590, 360, 251, 31))
        self.label_39.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_39.setObjectName("label_39")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_pacient)
        self.lineEdit_30.setGeometry(QtCore.QRect(510, 410, 311, 31))
        self.lineEdit_30.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.tabWidget_O.addTab(self.tab_pacient, "")
        self.tab_sizers = QtWidgets.QWidget()
        self.tab_sizers.setObjectName("tab_sizers")
        self.label_9 = QtWidgets.QLabel(self.tab_sizers)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 191, 51))
        self.label_9.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_sizers)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 191, 51))
        self.label_10.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_sizers)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 191, 51))
        self.label_11.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_sizers)
        self.label_12.setGeometry(QtCore.QRect(110, 250, 131, 51))
        self.label_12.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_sizers)
        self.label_13.setGeometry(QtCore.QRect(510, 250, 121, 51))
        self.label_13.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_sizers)
        self.lineEdit_10.setGeometry(QtCore.QRect(70, 340, 51, 31))
        self.lineEdit_10.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_sizers)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 340, 51, 31))
        self.lineEdit_11.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_sizers)
        self.lineEdit_12.setGeometry(QtCore.QRect(210, 340, 51, 31))
        self.lineEdit_12.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_sizers)
        self.lineEdit_13.setGeometry(QtCore.QRect(470, 340, 51, 31))
        self.lineEdit_13.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_sizers)
        self.lineEdit_14.setGeometry(QtCore.QRect(540, 340, 51, 31))
        self.lineEdit_14.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setText("")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_sizers)
        self.lineEdit_15.setGeometry(QtCore.QRect(610, 340, 51, 31))
        self.lineEdit_15.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_14 = QtWidgets.QLabel(self.tab_sizers)
        self.label_14.setGeometry(QtCore.QRect(280, 340, 31, 31))
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_sizers)
        self.label_15.setGeometry(QtCore.QRect(680, 340, 31, 31))
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.tab_sizers)
        self.label_17.setGeometry(QtCore.QRect(310, 250, 101, 41))
        self.label_17.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_sizers)
        self.lineEdit_17.setGeometry(QtCore.QRect(330, 300, 51, 31))
        self.lineEdit_17.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_18 = QtWidgets.QLabel(self.tab_sizers)
        self.label_18.setGeometry(QtCore.QRect(390, 300, 31, 31))
        self.label_18.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.tab_sizers)
        self.label_21.setGeometry(QtCore.QRect(10, 480, 141, 41))
        self.label_21.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_sizers)
        self.label_22.setGeometry(QtCore.QRect(10, 560, 141, 41))
        self.label_22.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_2.setGeometry(QtCore.QRect(240, 30, 241, 41))
        self.comboBox_2.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_3.setGeometry(QtCore.QRect(240, 100, 241, 41))
        self.comboBox_3.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_4.setGeometry(QtCore.QRect(240, 170, 141, 41))
        self.comboBox_4.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 480, 141, 41))
        self.comboBox_5.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_6.setGeometry(QtCore.QRect(350, 480, 321, 41))
        self.comboBox_6.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_7.setGeometry(QtCore.QRect(690, 480, 141, 41))
        self.comboBox_7.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_8.setGeometry(QtCore.QRect(180, 560, 221, 41))
        self.comboBox_8.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_9.setGeometry(QtCore.QRect(410, 560, 131, 41))
        self.comboBox_9.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_sizers)
        self.comboBox_10.setGeometry(QtCore.QRect(550, 560, 141, 41))
        self.comboBox_10.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.tabWidget_O.addTab(self.tab_sizers, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_O_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_O_2.setGeometry(QtCore.QRect(0, 0, 861, 691))
        self.tabWidget_O_2.setObjectName("tabWidget_O_2")
        self.tab_ochag_change_2 = QtWidgets.QWidget()
        self.tab_ochag_change_2.setObjectName("tab_ochag_change_2")
        self.label_75 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_75.setGeometry(QtCore.QRect(10, 10, 151, 51))
        self.label_75.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_76.setGeometry(QtCore.QRect(10, 90, 421, 41))
        self.label_76.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_76.setObjectName("label_76")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_ochag_change_2)
        self.lineEdit_43.setGeometry(QtCore.QRect(450, 100, 51, 31))
        self.lineEdit_43.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.label_77 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_77.setGeometry(QtCore.QRect(520, 100, 31, 31))
        self.label_77.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_78.setGeometry(QtCore.QRect(10, 200, 131, 31))
        self.label_78.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_78.setObjectName("label_78")
        self.label_79 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_79.setGeometry(QtCore.QRect(160, 150, 31, 31))
        self.label_79.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_80.setGeometry(QtCore.QRect(160, 200, 31, 31))
        self.label_80.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_81.setGeometry(QtCore.QRect(160, 250, 31, 31))
        self.label_81.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_81.setObjectName("label_81")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.tab_ochag_change_2)
        self.lineEdit_44.setGeometry(QtCore.QRect(220, 150, 51, 31))
        self.lineEdit_44.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.tab_ochag_change_2)
        self.lineEdit_45.setGeometry(QtCore.QRect(220, 200, 51, 31))
        self.lineEdit_45.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_ochag_change_2)
        self.lineEdit_46.setGeometry(QtCore.QRect(220, 250, 51, 31))
        self.lineEdit_46.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.label_83 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_83.setGeometry(QtCore.QRect(10, 330, 81, 31))
        self.label_83.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_84.setGeometry(QtCore.QRect(380, 330, 101, 31))
        self.label_84.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_85.setGeometry(QtCore.QRect(10, 400, 101, 31))
        self.label_85.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_85.setObjectName("label_85")
        self.label_86 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_86.setGeometry(QtCore.QRect(390, 400, 121, 31))
        self.label_86.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_86.setObjectName("label_86")
        self.comboBox_30 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_30.setGeometry(QtCore.QRect(180, 20, 301, 41))
        self.comboBox_30.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_30.setObjectName("comboBox_30")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_30.addItem("")
        self.comboBox_31 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_31.setGeometry(QtCore.QRect(110, 330, 221, 41))
        self.comboBox_31.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_31.setObjectName("comboBox_31")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_31.addItem("")
        self.comboBox_32 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_32.setGeometry(QtCore.QRect(120, 400, 221, 41))
        self.comboBox_32.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_32.setObjectName("comboBox_32")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_32.addItem("")
        self.comboBox_33 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_33.setGeometry(QtCore.QRect(490, 330, 221, 41))
        self.comboBox_33.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_33.setObjectName("comboBox_33")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_33.addItem("")
        self.comboBox_34 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_34.setGeometry(QtCore.QRect(510, 400, 221, 41))
        self.comboBox_34.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_34.setObjectName("comboBox_34")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_34.addItem("")
        self.comboBox_35 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_35.setGeometry(QtCore.QRect(120, 470, 221, 41))
        self.comboBox_35.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_35.setObjectName("comboBox_35")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.comboBox_35.addItem("")
        self.label_87 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_87.setGeometry(QtCore.QRect(10, 470, 121, 31))
        self.label_87.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_88.setGeometry(QtCore.QRect(420, 580, 121, 31))
        self.label_88.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_88.setText("")
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_89.setGeometry(QtCore.QRect(10, 550, 181, 31))
        self.label_89.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_90.setGeometry(QtCore.QRect(390, 480, 71, 31))
        self.label_90.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_90.setObjectName("label_90")
        self.comboBox_36 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_36.setGeometry(QtCore.QRect(200, 550, 221, 41))
        self.comboBox_36.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_36.setObjectName("comboBox_36")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_37 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_37.setGeometry(QtCore.QRect(470, 480, 221, 41))
        self.comboBox_37.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_37.setObjectName("comboBox_37")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.setItemText(5, "")
        self.comboBox_37.addItem("")
        self.comboBox_37.setItemText(6, "")
        self.label_91 = QtWidgets.QLabel(self.tab_ochag_change_2)
        self.label_91.setGeometry(QtCore.QRect(460, 560, 81, 31))
        self.label_91.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_91.setObjectName("label_91")
        self.comboBox_38 = QtWidgets.QComboBox(self.tab_ochag_change_2)
        self.comboBox_38.setGeometry(QtCore.QRect(540, 550, 221, 41))
        self.comboBox_38.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_38.setObjectName("comboBox_38")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.comboBox_38.addItem("")
        self.tabWidget_O_2.addTab(self.tab_ochag_change_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_126 = QtWidgets.QLabel(self.tab_3)
        self.label_126.setGeometry(QtCore.QRect(10, 10, 151, 51))
        self.label_126.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_126.setObjectName("label_126")
        self.comboBox_57 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_57.setGeometry(QtCore.QRect(180, 20, 301, 41))
        self.comboBox_57.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_57.setObjectName("comboBox_57")
        self.comboBox_57.addItem("")
        self.comboBox_57.addItem("")
        self.comboBox_57.addItem("")
        self.comboBox_57.addItem("")
        self.comboBox_57.addItem("")
        self.comboBox_57.addItem("")
        self.label_127 = QtWidgets.QLabel(self.tab_3)
        self.label_127.setGeometry(QtCore.QRect(10, 90, 421, 41))
        self.label_127.setStyleSheet("background-color: rgb(255, 209, 144);\n"
"border-radius:20px;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_127.setObjectName("label_127")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_58.setGeometry(QtCore.QRect(450, 100, 51, 31))
        self.lineEdit_58.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.label_128 = QtWidgets.QLabel(self.tab_3)
        self.label_128.setGeometry(QtCore.QRect(520, 100, 31, 31))
        self.label_128.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_128.setObjectName("label_128")
        self.label_129 = QtWidgets.QLabel(self.tab_3)
        self.label_129.setGeometry(QtCore.QRect(10, 190, 131, 31))
        self.label_129.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_129.setObjectName("label_129")
        self.label_130 = QtWidgets.QLabel(self.tab_3)
        self.label_130.setGeometry(QtCore.QRect(160, 160, 31, 31))
        self.label_130.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_130.setObjectName("label_130")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_59.setGeometry(QtCore.QRect(200, 160, 51, 31))
        self.lineEdit_59.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.label_131 = QtWidgets.QLabel(self.tab_3)
        self.label_131.setGeometry(QtCore.QRect(160, 200, 31, 31))
        self.label_131.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_131.setObjectName("label_131")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_60.setGeometry(QtCore.QRect(200, 200, 51, 31))
        self.lineEdit_60.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_61.setGeometry(QtCore.QRect(200, 240, 51, 31))
        self.lineEdit_61.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.label_132 = QtWidgets.QLabel(self.tab_3)
        self.label_132.setGeometry(QtCore.QRect(160, 240, 31, 31))
        self.label_132.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_132.setObjectName("label_132")
        self.label_134 = QtWidgets.QLabel(self.tab_3)
        self.label_134.setGeometry(QtCore.QRect(10, 320, 81, 31))
        self.label_134.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_134.setObjectName("label_134")
        self.comboBox_58 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_58.setGeometry(QtCore.QRect(100, 320, 221, 41))
        self.comboBox_58.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_58.setObjectName("comboBox_58")
        self.comboBox_58.addItem("")
        self.comboBox_58.addItem("")
        self.comboBox_58.addItem("")
        self.comboBox_58.addItem("")
        self.comboBox_58.addItem("")
        self.label_135 = QtWidgets.QLabel(self.tab_3)
        self.label_135.setGeometry(QtCore.QRect(410, 320, 101, 31))
        self.label_135.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_135.setObjectName("label_135")
        self.comboBox_59 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_59.setGeometry(QtCore.QRect(520, 320, 221, 41))
        self.comboBox_59.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_59.setObjectName("comboBox_59")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.comboBox_59.addItem("")
        self.label_136 = QtWidgets.QLabel(self.tab_3)
        self.label_136.setGeometry(QtCore.QRect(10, 390, 101, 31))
        self.label_136.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_136.setObjectName("label_136")
        self.comboBox_60 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_60.setGeometry(QtCore.QRect(120, 390, 221, 41))
        self.comboBox_60.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_60.setObjectName("comboBox_60")
        self.comboBox_60.addItem("")
        self.comboBox_60.addItem("")
        self.comboBox_60.addItem("")
        self.comboBox_60.addItem("")
        self.comboBox_60.addItem("")
        self.label_137 = QtWidgets.QLabel(self.tab_3)
        self.label_137.setGeometry(QtCore.QRect(420, 390, 121, 31))
        self.label_137.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_137.setObjectName("label_137")
        self.comboBox_61 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_61.setGeometry(QtCore.QRect(560, 390, 221, 41))
        self.comboBox_61.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_61.setObjectName("comboBox_61")
        self.comboBox_61.addItem("")
        self.comboBox_61.addItem("")
        self.comboBox_61.addItem("")
        self.comboBox_61.addItem("")
        self.comboBox_61.addItem("")
        self.comboBox_61.addItem("")
        self.comboBox_61.addItem("")
        self.label_138 = QtWidgets.QLabel(self.tab_3)
        self.label_138.setGeometry(QtCore.QRect(10, 460, 121, 31))
        self.label_138.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_138.setObjectName("label_138")
        self.comboBox_62 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_62.setGeometry(QtCore.QRect(120, 450, 221, 41))
        self.comboBox_62.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_62.setObjectName("comboBox_62")
        self.comboBox_62.addItem("")
        self.comboBox_62.addItem("")
        self.comboBox_62.addItem("")
        self.comboBox_62.addItem("")
        self.comboBox_62.addItem("")
        self.label_139 = QtWidgets.QLabel(self.tab_3)
        self.label_139.setGeometry(QtCore.QRect(10, 520, 181, 31))
        self.label_139.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_139.setObjectName("label_139")
        self.comboBox_63 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_63.setGeometry(QtCore.QRect(190, 520, 221, 41))
        self.comboBox_63.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_63.setObjectName("comboBox_63")
        self.comboBox_63.addItem("")
        self.comboBox_63.addItem("")
        self.comboBox_63.addItem("")
        self.comboBox_63.addItem("")
        self.label_140 = QtWidgets.QLabel(self.tab_3)
        self.label_140.setGeometry(QtCore.QRect(450, 450, 71, 31))
        self.label_140.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_140.setObjectName("label_140")
        self.comboBox_64 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_64.setGeometry(QtCore.QRect(510, 450, 221, 41))
        self.comboBox_64.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_64.setObjectName("comboBox_64")
        self.comboBox_64.addItem("")
        self.comboBox_64.addItem("")
        self.comboBox_64.addItem("")
        self.comboBox_64.addItem("")
        self.comboBox_64.addItem("")
        self.comboBox_64.addItem("")
        self.comboBox_64.setItemText(5, "")
        self.comboBox_64.addItem("")
        self.comboBox_64.setItemText(6, "")
        self.label_141 = QtWidgets.QLabel(self.tab_3)
        self.label_141.setGeometry(QtCore.QRect(450, 520, 81, 31))
        self.label_141.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_141.setObjectName("label_141")
        self.comboBox_65 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_65.setGeometry(QtCore.QRect(530, 520, 221, 41))
        self.comboBox_65.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"color: rgb(255, 215, 111);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.comboBox_65.setObjectName("comboBox_65")
        self.comboBox_65.addItem("")
        self.comboBox_65.addItem("")
        self.comboBox_65.addItem("")
        self.comboBox_65.addItem("")
        self.comboBox_65.addItem("")
        self.comboBox_65.addItem("")
        self.tabWidget_O_2.addTab(self.tab_3, "")
        self.tabWidget_O.addTab(self.tab_2, "")
        self.tab_limf_usly = QtWidgets.QWidget()
        self.tab_limf_usly.setObjectName("tab_limf_usly")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab_limf_usly)
        self.textEdit_6.setGeometry(QtCore.QRect(130, 120, 591, 321))
        self.textEdit_6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_38 = QtWidgets.QLabel(self.tab_limf_usly)
        self.label_38.setGeometry(QtCore.QRect(310, 70, 211, 31))
        self.label_38.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_38.setObjectName("label_38")
        self.tabWidget_O.addTab(self.tab_limf_usly, "")
        self.tab_potalog_obraz = QtWidgets.QWidget()
        self.tab_potalog_obraz.setObjectName("tab_potalog_obraz")
        self.textEdit = QtWidgets.QTextEdit(self.tab_potalog_obraz)
        self.textEdit.setGeometry(QtCore.QRect(140, 170, 571, 201))
        self.textEdit.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.label_8 = QtWidgets.QLabel(self.tab_potalog_obraz)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 281, 41))
        self.label_8.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(13, 13, 13);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_8.setObjectName("label_8")
        self.tabWidget_O.addTab(self.tab_potalog_obraz, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setGeometry(QtCore.QRect(350, 80, 281, 41))
        self.label_43.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(13, 13, 13);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_43.setObjectName("label_43")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_7.setGeometry(QtCore.QRect(140, 160, 571, 201))
        self.textEdit_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.textEdit_7.setObjectName("textEdit_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 0, 191, 51))
        self.pushButton_5.setStyleSheet("background-color: rgb(190, 255, 178);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget_O.addTab(self.tab, "")
        self.label = QtWidgets.QLabel(self.USI)
        self.label.setGeometry(QtCore.QRect(0, -10, 391, 61))
        self.label.setStyleSheet("color: rgb(255, 92, 92);\n"
"font: 28pt \"Palatino Linotype\";\n"
"background-color: rgba(255, 255, 255, 0);\n"
"border-radius:5px;\n"
"border-color: rgb(255, 175, 46);")
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.USI, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_O.setCurrentIndex(2)
        self.tabWidget_O_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit_resultat.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MV Boli\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lineEdit_res_2.setText(_translate("MainWindow", "Результат:"))
        self.pushButton_4.setText(_translate("MainWindow", "Печать"))
        self.pushButton_4.clicked.connect(self.printprint)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), _translate("MainWindow", "Home"))
        self.label_2.setText(_translate("MainWindow", "Ф. И. О. - "))
        self.label_3.setText(_translate("MainWindow", "Возраст - "))
        self.label_4.setText(_translate("MainWindow", "Пол - "))
        self.comboBox.setItemText(0, _translate("MainWindow", "ЖЕН"))
        self.comboBox.setItemText(1, _translate("MainWindow", "МУЖ"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Не Указан"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Другое"))
        self.label_5.setText(_translate("MainWindow", "Рост - "))
        self.lineEdit_4.setText(_translate("MainWindow", "Не Указан"))
        self.lineEdit_5.setText(_translate("MainWindow", "Не Указан"))
        self.label_6.setText(_translate("MainWindow", "Вес - "))
        self.label_7.setText(_translate("MainWindow", "Дата Обслед. - "))
        self.lineEdit_6.setText(_translate("MainWindow", "Не Указан"))
        self.label_36.setText(_translate("MainWindow", "Врач:"))
        self.label_37.setText(_translate("MainWindow", "Место  обследования:"))
        self.label_39.setText(_translate("MainWindow", "Тип  датчика:"))
        self.tabWidget_O.setTabText(self.tabWidget_O.indexOf(self.tab_pacient), _translate("MainWindow", "Пациент"))
        self.label_9.setText(_translate("MainWindow", "Расположение ЩЖ - "))
        self.label_10.setText(_translate("MainWindow", "Форма ЩЖ - "))
        self.label_11.setText(_translate("MainWindow", "Контуры ЩЖ - "))
        self.label_12.setText(_translate("MainWindow", "Правая Доля"))
        self.label_13.setText(_translate("MainWindow", "Левая Доля"))
        self.label_14.setText(_translate("MainWindow", "мм"))
        self.label_15.setText(_translate("MainWindow", "мм"))
        self.label_17.setText(_translate("MainWindow", "Перешеек"))
        self.label_18.setText(_translate("MainWindow", "мм"))
        self.label_21.setText(_translate("MainWindow", "Эхогенность - "))
        self.label_22.setText(_translate("MainWindow", "Эхоструктура - "))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "типичное(2-3 см. выше ключицы)"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "частично загрудинно(н/полюса)         "))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "загрудинно"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "классическая(2 доли и перешеек)"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "одна доля:правая / левая"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "участки тиреоидной ткани"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "щ/ж не лоцируется"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "ровные/чёткие"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "ровные/нечёткие"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "неровные/чёткие"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "неровные/нечёткие"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "нормальная"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "повышена"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "понижена"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "смешанная"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "степень изменения эхогенности незначительная"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "степень изменения эхогенности умеренная"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "степень изменения эхогенности выраженная"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "локальная"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "диффузная"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "эхооднородная мелкозернистая"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "неоднородная - мелкоочагово"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "неоднородная - крупноочагово"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "незначительная"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "умеренная"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "выраженная"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "локальная"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "диффузная"))
        self.tabWidget_O.setTabText(self.tabWidget_O.indexOf(self.tab_sizers), _translate("MainWindow", "Размеры ЩЖ"))
        self.label_75.setText(_translate("MainWindow", "Локализация - "))
        self.label_76.setText(_translate("MainWindow", "Глубина расположения от поверхности кожи - "))
        self.lineEdit_43.setText(_translate("MainWindow", "-"))
        self.label_77.setText(_translate("MainWindow", "мм"))
        self.label_78.setText(_translate("MainWindow", "Размеры (мм)"))
        self.label_79.setText(_translate("MainWindow", "Д"))
        self.label_80.setText(_translate("MainWindow", "Т"))
        self.label_81.setText(_translate("MainWindow", "Ш"))
        self.lineEdit_44.setText(_translate("MainWindow", "-"))
        self.lineEdit_45.setText(_translate("MainWindow", "-"))
        self.lineEdit_46.setText(_translate("MainWindow", "-"))
        self.label_83.setText(_translate("MainWindow", "Форма - "))
        self.label_84.setText(_translate("MainWindow", "Контуры - "))
        self.label_85.setText(_translate("MainWindow", "Эхогенность - "))
        self.label_86.setText(_translate("MainWindow", "Эхоструктура - "))
        self.comboBox_30.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_30.setItemText(1, _translate("MainWindow", "в правой доле"))
        self.comboBox_30.setItemText(2, _translate("MainWindow", "в левой доле"))
        self.comboBox_30.setItemText(3, _translate("MainWindow", "на переходе правой доли в перешеек"))
        self.comboBox_30.setItemText(4, _translate("MainWindow", "на переходе левой доли в перешеек"))
        self.comboBox_30.setItemText(5, _translate("MainWindow", "на перешееке"))
        self.comboBox_31.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_31.setItemText(1, _translate("MainWindow", "округлая"))
        self.comboBox_31.setItemText(2, _translate("MainWindow", "овальная - вертикальный рост"))
        self.comboBox_31.setItemText(3, _translate("MainWindow", "овальная - горизонтальный рост"))
        self.comboBox_31.setItemText(4, _translate("MainWindow", "неправильной формы"))
        self.comboBox_32.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_32.setItemText(1, _translate("MainWindow", "изоэхогенная"))
        self.comboBox_32.setItemText(2, _translate("MainWindow", "гиперэхогенная"))
        self.comboBox_32.setItemText(3, _translate("MainWindow", "гипоэхогенная"))
        self.comboBox_32.setItemText(4, _translate("MainWindow", "анэхогенная"))
        self.comboBox_33.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_33.setItemText(1, _translate("MainWindow", "четкие, ровные"))
        self.comboBox_33.setItemText(2, _translate("MainWindow", "четкие, неровные"))
        self.comboBox_33.setItemText(3, _translate("MainWindow", "нечёткие, ровные"))
        self.comboBox_33.setItemText(4, _translate("MainWindow", "нечёткие, неровные"))
        self.comboBox_33.setItemText(5, _translate("MainWindow", "размытые"))
        self.comboBox_33.setItemText(6, _translate("MainWindow", "неровный лучистый"))
        self.comboBox_33.setItemText(7, _translate("MainWindow", "неровный звёздчатый"))
        self.comboBox_33.setItemText(8, _translate("MainWindow", "неровный бугристый"))
        self.comboBox_33.setItemText(9, _translate("MainWindow", "неровный микродольчатый"))
        self.comboBox_34.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_34.setItemText(1, _translate("MainWindow", "солидная однородная"))
        self.comboBox_34.setItemText(2, _translate("MainWindow", "солидная неоднородная"))
        self.comboBox_34.setItemText(3, _translate("MainWindow", "солидно-кистозная"))
        self.comboBox_34.setItemText(4, _translate("MainWindow", "кистозно-солидная"))
        self.comboBox_34.setItemText(5, _translate("MainWindow", "преимущтвенно кистозная"))
        self.comboBox_34.setItemText(6, _translate("MainWindow", "кистозная"))
        self.comboBox_35.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_35.setItemText(1, _translate("MainWindow", "Микрокальцинаты < 1,0мм"))
        self.comboBox_35.setItemText(2, _translate("MainWindow", "Макрокальцинаты > 1,0мм"))
        self.comboBox_35.setItemText(3, _translate("MainWindow", "Кальцинорованные участки"))
        self.comboBox_35.setItemText(4, _translate("MainWindow", "по типу \"яичной скорлупы\""))
        self.label_87.setText(_translate("MainWindow", "Кальцинаты - "))
        self.label_89.setText(_translate("MainWindow", "Акустические эффекты - "))
        self.label_90.setText(_translate("MainWindow", "Хало - "))
        self.comboBox_36.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_36.setItemText(1, _translate("MainWindow", "Дорсальное усиление"))
        self.comboBox_36.setItemText(2, _translate("MainWindow", "Дорсальное ослабление"))
        self.comboBox_36.setItemText(3, _translate("MainWindow", "\"Хвост кометы\""))
        self.comboBox_37.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_37.setItemText(1, _translate("MainWindow", "Отсутсвует"))
        self.comboBox_37.setItemText(2, _translate("MainWindow", "тонкое - непрерывное"))
        self.comboBox_37.setItemText(3, _translate("MainWindow", "тонкое - прерывистое"))
        self.comboBox_37.setItemText(4, _translate("MainWindow", "неравномерно утолщенное"))
        self.label_91.setText(_translate("MainWindow", "ЦДК/ЭК - "))
        self.comboBox_38.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_38.setItemText(1, _translate("MainWindow", "Перинодулярный"))
        self.comboBox_38.setItemText(2, _translate("MainWindow", "Интронодулярный-Периф."))
        self.comboBox_38.setItemText(3, _translate("MainWindow", "Интронодулярный-Центр."))
        self.comboBox_38.setItemText(4, _translate("MainWindow", "Интронодулярный-Смеш."))
        self.comboBox_38.setItemText(5, _translate("MainWindow", "Хаотичный кровоток"))
        self.tabWidget_O_2.setTabText(self.tabWidget_O_2.indexOf(self.tab_ochag_change_2), _translate("MainWindow", "1"))
        # self.label_126.setText(_translate("MainWindow", "Локализация - "))
        # self.comboBox_57.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_57.setItemText(1, _translate("MainWindow", "в правой доле"))
        # self.comboBox_57.setItemText(2, _translate("MainWindow", "в левой доле"))
        # self.comboBox_57.setItemText(3, _translate("MainWindow", "на переходе правой доли в перешеек"))
        # self.comboBox_57.setItemText(4, _translate("MainWindow", "на переходе левой доли в перешеек"))
        # self.comboBox_57.setItemText(5, _translate("MainWindow", "на перешееке"))
        # self.label_127.setText(_translate("MainWindow", "Глубина расположения от поверхности кожи - "))
        # self.lineEdit_58.setText(_translate("MainWindow", "-"))
        # self.label_128.setText(_translate("MainWindow", "мм"))
        # self.label_129.setText(_translate("MainWindow", "Размеры (мм)"))
        # self.label_130.setText(_translate("MainWindow", "Д"))
        # self.lineEdit_59.setText(_translate("MainWindow", "-"))
        # self.label_131.setText(_translate("MainWindow", "Т"))
        # self.lineEdit_60.setText(_translate("MainWindow", "-"))
        # self.lineEdit_61.setText(_translate("MainWindow", "-"))
        # self.label_132.setText(_translate("MainWindow", "Ш"))
        # self.label_134.setText(_translate("MainWindow", "Форма - "))
        # self.comboBox_58.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_58.setItemText(1, _translate("MainWindow", "округлая"))
        # self.comboBox_58.setItemText(2, _translate("MainWindow", "овальная - вертикальный рост"))
        # self.comboBox_58.setItemText(3, _translate("MainWindow", "овальная - горизонтальный рост"))
        # self.comboBox_58.setItemText(4, _translate("MainWindow", "неправильной формы"))
        # self.label_135.setText(_translate("MainWindow", "Контуры - "))
        # self.comboBox_59.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_59.setItemText(1, _translate("MainWindow", "четкие, ровные"))
        # self.comboBox_59.setItemText(2, _translate("MainWindow", "четкие, неровные"))
        # self.comboBox_59.setItemText(3, _translate("MainWindow", "нечёткие, ровные"))
        # self.comboBox_59.setItemText(4, _translate("MainWindow", "нечёткие, неровные"))
        # self.comboBox_59.setItemText(5, _translate("MainWindow", "размытые"))
        # self.comboBox_59.setItemText(6, _translate("MainWindow", "неровный лучистый"))
        # self.comboBox_59.setItemText(7, _translate("MainWindow", "неровный звёздчатый"))
        # self.comboBox_59.setItemText(8, _translate("MainWindow", "неровный бугристый"))
        # self.comboBox_59.setItemText(9, _translate("MainWindow", "неровный микродольчатый"))
        # self.label_136.setText(_translate("MainWindow", "Эхогенность - "))
        # self.comboBox_60.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_60.setItemText(1, _translate("MainWindow", "изоэхогенная"))
        # self.comboBox_60.setItemText(2, _translate("MainWindow", "гиперэхогенная"))
        # self.comboBox_60.setItemText(3, _translate("MainWindow", "гипоэхогенная"))
        # self.comboBox_60.setItemText(4, _translate("MainWindow", "анэхогенная"))
        # self.label_137.setText(_translate("MainWindow", "Эхоструктура - "))
        # self.comboBox_61.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_61.setItemText(1, _translate("MainWindow", "солидная однородная"))
        # self.comboBox_61.setItemText(2, _translate("MainWindow", "солидная неоднородная"))
        # self.comboBox_61.setItemText(3, _translate("MainWindow", "солидно-кистозная"))
        # self.comboBox_61.setItemText(4, _translate("MainWindow", "кистозно-солидная"))
        # self.comboBox_61.setItemText(5, _translate("MainWindow", "преимущтвенно кистозная"))
        # self.comboBox_61.setItemText(6, _translate("MainWindow", "кистозная"))
        # self.label_138.setText(_translate("MainWindow", "Кальцинаты - "))
        # self.comboBox_62.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_62.setItemText(1, _translate("MainWindow", "Микрокальцинаты < 1,0мм"))
        # self.comboBox_62.setItemText(2, _translate("MainWindow", "Макрокальцинаты > 1,0мм"))
        # self.comboBox_62.setItemText(3, _translate("MainWindow", "Кальцинорованные участки"))
        # self.comboBox_62.setItemText(4, _translate("MainWindow", "по типу \"яичной скорлупы\""))
        # self.label_139.setText(_translate("MainWindow", "Акустические эффекты - "))
        # self.comboBox_63.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_63.setItemText(1, _translate("MainWindow", "Дорсальное усиление"))
        # self.comboBox_63.setItemText(2, _translate("MainWindow", "Дорсальное ослабление"))
        # self.comboBox_63.setItemText(3, _translate("MainWindow", "\"Хвост кометы\""))
        # self.label_140.setText(_translate("MainWindow", "Хало - "))
        # self.comboBox_64.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_64.setItemText(1, _translate("MainWindow", "Отсутсвует"))
        # self.comboBox_64.setItemText(2, _translate("MainWindow", "тонкое - непрерывное"))
        # self.comboBox_64.setItemText(3, _translate("MainWindow", "тонкое - прерывистое"))
        # self.comboBox_64.setItemText(4, _translate("MainWindow", "неравномерно утолщенное"))
        # self.label_141.setText(_translate("MainWindow", "ЦДК/ЭК - "))
        # self.comboBox_65.setItemText(0, _translate("MainWindow", "-"))
        # self.comboBox_65.setItemText(1, _translate("MainWindow", "Перинодулярный"))
        # self.comboBox_65.setItemText(2, _translate("MainWindow", "Интронодулярный-Периф."))
        # self.comboBox_65.setItemText(3, _translate("MainWindow", "Интронодулярный-Центр."))
        # self.comboBox_65.setItemText(4, _translate("MainWindow", "Интронодулярный-Смеш."))
        # self.comboBox_65.setItemText(5, _translate("MainWindow", "Хаотичный кровоток"))
        # self.tabWidget_O_2.setTabText(self.tabWidget_O_2.indexOf(self.tab_3), _translate("MainWindow", "2"))
        self.tabWidget_O.setTabText(self.tabWidget_O.indexOf(self.tab_2), _translate("MainWindow", "Очаговые Изменения"))
        self.label_38.setText(_translate("MainWindow", "Лимфатические узлы:"))
        self.tabWidget_O.setTabText(self.tabWidget_O.indexOf(self.tab_limf_usly), _translate("MainWindow", "Лимфатические Узлы"))
        self.label_8.setText(_translate("MainWindow", "Поталогические изменения:"))
        self.tabWidget_O.setTabText(self.tabWidget_O.indexOf(self.tab_potalog_obraz), _translate("MainWindow", "Поталогич. образования"))
        self.label_43.setText(_translate("MainWindow", "Заключение:"))
        self.pushButton_5.setText(_translate("MainWindow", "Печать"))
        self.pushButton_5.clicked.connect(self.Set_TextRes)
        self.tabWidget_O.setTabText(self.tabWidget_O.indexOf(self.tab), _translate("MainWindow", "ЗАКЛЮЧЕНИЕ"))
        self.label.setText(_translate("MainWindow", "Щитовидная железа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.USI), _translate("MainWindow", "Щитовидная железа"))


    # def currentIndexChanged(self):
    #     return self.comboBox.currentText()


    def Set_TextRes(self): 
        self.valO1 = str(eval(f"{self.lineEdit_10.text()} * {self.lineEdit_11.text()} * {self.lineEdit_12.text()} * 0.479"))
        self.valO2 = str(eval(f"{self.lineEdit_13.text()} * {self.lineEdit_14.text()} * {self.lineEdit_15.text()} * 0.479"))
        self.val_tog = int(eval(f"{self.valO1} + {self.valO2}"))

        self.protocol = f"""\t\t\t\t\t\t\tТип датчика {self.lineEdit_30.text()}

            ФИО {self.lineEdit_2.text()} возраст  {self.lineEdit_3.text()}
            Пол {self.comboBox.currentText()} Рост-Вес  {self.lineEdit_4.text()} см - {self.lineEdit_5.text()} кг

            1.Расположение железы:                  2. Анатомическая форма:        
            {self.comboBox_2.currentText()}         {self.comboBox_3.currentText()}

            3.Контуры:
            {self.comboBox_4.currentText()}

            4.Размеры
            Правая доля толщина {self.lineEdit_10.text()} мм, ширина {(self.lineEdit_11.text())} мм, длина {(self.lineEdit_12.text())} мм, объем {self.valO1[0] + "," + self.valO1[1:3]} см3
            Левая доля толщина {self.lineEdit_13.text()} мм, ширина {(self.lineEdit_14.text())} мм, длина {(self.lineEdit_15.text())} мм, объем {self.valO2[0] + "," + self.valO2[1:3]} см3
            Перешеек толщина {(self.lineEdit_17.text())} мм.   ОБЩИЙ  ОБЪЕМ {round(self.val_tog)} см3
            
            5.Эхогенность паренхимы:
            {self.comboBox_5.currentText()}, {self.comboBox_6.currentText()}, {self.comboBox_7.currentText()}
            6.Эхоструктура:            
            {self.comboBox_8.currentText()}, {self.comboBox_9.currentText()}, {self.comboBox_10.currentText()}   7.Лимфоузлы {str(self.textEdit_6.toPlainText())}
            
            8. Объемные образования:
            Локализация = {self.comboBox_30.currentText()}    Глубина расположения от поверхности кожи = {self.lineEdit_43.text()}
            Размеры (мм) Длина {self.lineEdit_44.text()}, Толщина {self.lineEdit_45.text()}, Ширина {self.lineEdit_46.text()}
            форма - {self.comboBox_31.currentText()}, контуры - {self.comboBox_33.currentText()}, Эхогенность - {self.comboBox_32.currentText()}, Эхоструктура - {self.comboBox_34.currentText()} 
            Кальцинаты - {self.comboBox_35.currentText()}, Хало - {self.comboBox_37.currentText()}, Акустические эффекты - {self.comboBox_36.currentText()}, ЦДК/ЭК - {self.comboBox_38.currentText()}
            
            Дополнительно:
            {str(self.textEdit.toPlainText())}
            Заключение:
            {str(self.textEdit_7.toPlainText())}

            Врач УЗД  {self.lineEdit_27.text()}

            Подпись_____________                               дата обследования {str(datetime.now()).split(".")[0]}
                    """


        self.textEdit_resultat.setText(self.protocol)

        document = Document()

        document.add_paragraph(f"                                                       {self.lineEdit_28.text()}")
        document.add_heading("ПРОТОКОЛ УЗИ ЩИТОВИДНОЙ ЖЕЛЕЗЫ") 
        self.filename = f"{self.lineEdit_2.text()}.docx"
        document.add_paragraph(self.protocol)
        document.save(self.filename)


    def printprint(self):
        self.fily = open(self.filename, 'r').read()
        win32api.ShellExecute(0, "printto", self.fily, '"&s"' & win32print.GetDefaultPrinter (), ".", 0)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())